=== velocitycareerlabs/velocitycore/packages/common-schemas/src/issuing/w3c-vc.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://velocitycareerlabs.io/w3c-vc.schema.json",
  "type": "object",
  "title": "w3c-vc",
  "description": "An w3c vc schema",
  "additionalProperties": true,
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "The JSON-LD context of the credential. @context is defaulted based on the VN credential metadata for the type chosen below"
    },
    "type": {
      "type": "array",
      "description": "The JSON-LD type of the credential.",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "credentialSubject": {
      "type": "object",
      "description": "Contains all the claims of the credential",
      "additionalProperties": true
    },
    "validUntil": {
      "type": "string",
      "format": "date-time"
    },
    "validFrom": {
      "type": "string",
      "format": "date-time"
    },
    "name": {
      "type": "string"
    },
    "issuer": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "type": {
          "anyOf": [
            {
              "type": "string",
              "description": "the type of the issuer property"
            },
            {
              "type": "array",
              "items": { "type": "string" }
            }
          ]
        },
        "id": {
          "type": "string",
          "description": "The issuer id."
        },
        "name": {
          "type": "string",
          "description": "The name of brand"
        },
        "image": {
          "type": "string",
          "description": "The uri to image"
        }
      }
    },
    "replaces": {
      "type": "array",
      "items": {
        "$ref": "https://velocitycareerlabs.io/new-offer-related-resource.schema.json#"
      }
    },
    "relatedResource": {
      "type": "array",
      "items": {
        "$ref": "https://velocitycareerlabs.io/new-offer-related-resource.schema.json#"
      }
    },
    "description": {
      "type": "string"
    },
    "image": {
      "type": "string",
      "format": "uri"
    },
    "awardedDate": {
      "type": "string",
      "format": "date-time"
    },
    "endorsement": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    },
    "endorsementJwt": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "evidence": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    },
    "credentialSchema": {
      "oneOf": [{
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uri"
          },
          "type": {
            "type": "string"
          }
        }
      }, {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "format": "uri"
            },
            "type": {
              "type": "string"
            }
          }
        }
      }]
    },
    "credentialStatus": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uri"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "refreshService": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uri"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "termsOfUrl": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "expirationDate": {
      "type": "string",
      "format": "date-time",
      "deprecated": true
    },
    "linkedCredentials": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "linkedCredentialId": {
            "type": "string"
          },
          "linkType": {
            "type": "string",
            "enum": [
              "REPLACE"
            ]
          }
        },
        "required": [
          "linkedCredentialId",
          "linkType"
        ]
      },
      "deprecated": true
    }
  },
  "required": [
    "type",
    "credentialSubject"
  ]
}

=== velocitycareerlabs/velocitycore/servers/credentialagent/test/data/open-badge-credential-example.json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "https://purl.imsglobal.org/spec/ob/v3p0/context-3.1.0.json"
  ],
  "type": ["OpenBadgeCredential", "AchievementCredential"],
  "credentialSubject": {
    "achievement": {
      "type": "Achievement",
      "id": "https://velocitynetwork.foundation/credentials/openbadgecredential-5",
      "name": "Wallet Passed VN Plugfest 2024",
      "description": "This wallet can display this Open Badge 3.0",
      "criteria": {
        "narrative": "The first cohort of the JFF Plugfest 1 in May/June of 2021 collaborated to push interoperability of VCs in education forward."
      },
      "image": {
        "id": "https://w3c-ccg.github.io/vc-ed/plugfest-1-2022/images/plugfest-1-badge-image.png",
        "type": "Image"
      }
    }
  },
  "name": "Wallet VN Plugfest 2024",
  "description": "Wallets are great when they interoperate",
  "image": "https://example.org/image.jpg",
  "awardedDate": "2024-10-01T09:00:00.001Z",
  "endorsement": [
    {
      "@context": [
        "https://www.w3.org/ns/credentials/v2",
        "https://purl.imsglobal.org/spec/ob/v3p0/context-3.1.0.json"
      ],
      "type": ["VerifiableCredential", "EndorsementCredential"]
    }
  ],
  "endorsementJwt": [
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJuYW1lIjoiZW5kb3JzZW1lbnQiLCJpYXQiOjE3MjU0MjgwODJ9.2SSU_WYSmXobZ3xLCzQYzmciFL3IAuAl9lfJPYM1JSbwa4itJNP9CaphUhimqaLiSmS5fZYtcdLDlEGWpMghyw"
  ],
  "evidence": [
    {
      "id": "https://example.com/evidence-3219839112",
      "type": ["Evidence"],
      "narrative": "blah blah blah",
      "name": "Big Evidence",
      "audience": "Everybody"
    }
  ],
  "credentialSchema": {
    "type": "1EdTechJsonSchemaValidator2019",
    "id": "http://example.com/schema.json"
  },
  "credentialStatus": {
    "type": "1EdTechRevocationList",
    "id": "https://example.edu/revocations/24"
  },
  "refreshService": {
    "type": "1EdTechCredentialRefresh",
    "id": "http://agent.example.com/refresh-service"
  }
}
